//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DormitoryDatabase : DbContext
    {
        public DormitoryDatabase()
            : base("name=DormitoryDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuButtonModel> MenuButtons { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<EmployeeLog> EmployeeLogs { get; set; }
        public virtual DbSet<DormitoryInfo> DormitoryInfos { get; set; }
        public virtual DbSet<Dormitory> Dormitories { get; set; }
        public virtual DbSet<UniversityInfo> UniversityInfos { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Human> Humans { get; set; }
    }
}
