//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public int ELID { get; set; }
        public string Description { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<int> RoomRID { get; set; }
        public int EmployeeHID { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
