//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityInfo
    {
        public int UIID { get; set; }
        public string University { get; set; }
        public string Faculty { get; set; }
        public string Specialty { get; set; }
        public int GroupNumber { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
