//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.DATABASE_BACKUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public short Permission { get; set; }
    
        public virtual Human Human { get; set; }
    }
}
