//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.DATABASE_BACKUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryInfo
    {
        public int DIID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> DormitoryDID { get; set; }
        public Nullable<int> RoomRID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Dormitory Dormitory { get; set; }
        public virtual Room Room { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
