//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.DATABASE_BACKUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuButtonModel
    {
        public int MBID { get; set; }
        public string Caption { get; set; }
        public string ImageSource { get; set; }
        public short Permission { get; set; }
        public string ViewName { get; set; }
    }
}
