//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DormitoryModel()
        {
            this.NumberOfFloors = 1;
            this.RoomsPerFloor = 1;
            this.CitizensPerRoom = 1;
            this.RoomModel = new HashSet<RoomModel>();
            this.EmployeeModel = new HashSet<EmployeeModel>();
        }
    
        public int DID { get; set; }
        public string Name { get; set; }
        public int NumberOfFloors { get; set; }
        public int RoomsPerFloor { get; set; }
        public int CitizensPerRoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomModel> RoomModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeModel> EmployeeModel { get; set; }
    }
}
