//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomModel()
        {
            this.ResidentModel = new HashSet<ResidentModel>();
            this.EmployeeLogModel = new HashSet<EmployeeLogModel>();
        }
    
        public int RID { get; set; }
        public int Number { get; set; }
        public int Floor { get; set; }
        public int DormitoryModelDID { get; set; }
        public double HeatSupply { get; set; }
        public double Electricity { get; set; }
    
        public virtual DormitoryModel DormitoryModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentModel> ResidentModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLogModel> EmployeeLogModel { get; set; }
    }
}
