//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModel
    {
        public int UID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public short Permission { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
    
        public virtual EmployeeModel EmployeeModel { get; set; }
        public virtual ResidentModel ResidentModel { get; set; }
    }
}
